-- MySQL Script generated by MySQL Workbench
-- 06/11/15 11:00:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecbookdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecbookdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecbookdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_estonian_ci ;
USE `ecbookdb` ;

-- -----------------------------------------------------
-- Table `ecbookdb`.`abteilung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`abteilung` (
  `abt_bezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `abt_kuerzel` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `abt_vorstand` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `abt_l_lehrernummer` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  PRIMARY KEY (`abt_bezeichnung`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbookdb`.`benutzergruppe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`benutzergruppe` (
  `bg_id` INT(11) NOT NULL AUTO_INCREMENT,
  `bg_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `bg_value` INT(11) NOT NULL,
  PRIMARY KEY (`bg_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbookdb`.`eltern`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`eltern` (
  `e_id` INT(11) NOT NULL AUTO_INCREMENT,
  `e_nachname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `e_vorname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `e_anrede` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `e_titel` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`e_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbookdb`.`klasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`klasse` (
  `k_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `k_jahrgang` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `k_abschlussjahr` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `k_schueleranzahl` INT(11) NULL DEFAULT NULL,
  `k_abt_bezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `k_semester` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`k_name`),
  INDEX `fk_Klasse_Abteilung1_idx` (`k_abt_bezeichnung` ASC),
  CONSTRAINT `fk_Klasse_Abteilung1`
    FOREIGN KEY (`k_abt_bezeichnung`)
    REFERENCES `ecbookdb`.`abteilung` (`abt_bezeichnung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbookdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `auth_key` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `password_hash` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `password_reset_token` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `email` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `status` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `benutzergruppe` INT(45) NOT NULL,
  `created_at` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `updated_at` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `vorname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `nachname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `geburtsdatum` DATE NULL DEFAULT NULL,
  `istKlassenvorstand` TINYINT(1) NULL DEFAULT NULL,
  `wohnadresse` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `telefonnummer` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `ort` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `plz` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `Abteilung_abt_bezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `Eltern_e_id` INT(11) NULL DEFAULT NULL,
  `istKlassensprecher` TINYINT(1) NULL DEFAULT NULL,
  `Klasse_k_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_Abteilung1_idx` (`Abteilung_abt_bezeichnung` ASC),
  INDEX `fk_user_Eltern1_idx` (`Eltern_e_id` ASC),
  INDEX `fk_user_Klasse1_idx` (`Klasse_k_name` ASC),
  INDEX `benutzergruppe` (`benutzergruppe` ASC),
  CONSTRAINT `fk_user_abteilung`
    FOREIGN KEY (`Abteilung_abt_bezeichnung`)
    REFERENCES `ecbookdb`.`abteilung` (`abt_bezeichnung`),
  CONSTRAINT `fk_user_benutzergruppe`
    FOREIGN KEY (`benutzergruppe`)
    REFERENCES `ecbookdb`.`benutzergruppe` (`bg_id`),
  CONSTRAINT `fk_user_eltern`
    FOREIGN KEY (`Eltern_e_id`)
    REFERENCES `ecbookdb`.`eltern` (`e_id`),
  CONSTRAINT `fk_user_klasse`
    FOREIGN KEY (`Klasse_k_name`)
    REFERENCES `ecbookdb`.`klasse` (`k_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbookdb`.`fehlstunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`fehlstunde` (
  `fs_datum` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fs_grund` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `fs_anzahl` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `fs_anmerkung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `fs_verspaetet` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`fs_datum`),
  INDEX `fk_Fehlstunde_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecbookdb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbookdb`.`krankmeldung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`krankmeldung` (
  `km_id` INT(11) NOT NULL AUTO_INCREMENT,
  `km_datum` TIMESTAMP NULL DEFAULT NULL,
  `km_unterschrift` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`km_id`),
  INDEX `fk_Krankmeldung_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_id1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecbookdb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbookdb`.`unterrichtsfach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`unterrichtsfach` (
  `uf_kurzbezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `uf_bezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `uf_jahrgang` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `uf_stundenanzahlprowoche` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`uf_kurzbezeichnung`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbookdb`.`pruefungen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`pruefungen` (
  `p_datum` DATE NOT NULL,
  `p_uhrzeit` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `p_thema` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `uf_kurzbezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  PRIMARY KEY (`p_datum`),
  INDEX `fk_Prüfungen_Unterrichtsfach1_idx` (`uf_kurzbezeichnung` ASC),
  CONSTRAINT `fk_Prüfungen_Unterrichtsfach1`
    FOREIGN KEY (`uf_kurzbezeichnung`)
    REFERENCES `ecbookdb`.`unterrichtsfach` (`uf_kurzbezeichnung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbookdb`.`unterrichtsstunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`unterrichtsstunde` (
  `us_id` INT(11) NOT NULL AUTO_INCREMENT,
  `us_std_datum` DATE NOT NULL,
  `us_stunde` INT(11) NOT NULL,
  `us_kurzbezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `us_raum` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `us_thema` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `k_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `uf_kurzbezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`us_id`),
  INDEX `fk_Unterrichtsstunde_has_Unterrichtsfach_Klasse1_idx` (`k_name` ASC),
  INDEX `fk_Unterrichtsstunde_Unterrichtsfach1_idx` (`uf_kurzbezeichnung` ASC),
  INDEX `fk_Unterrichtsstunde_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Unterrichtsstunde_Unterrichtsfach1`
    FOREIGN KEY (`uf_kurzbezeichnung`)
    REFERENCES `ecbookdb`.`unterrichtsfach` (`uf_kurzbezeichnung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Unterrichtsstunde_has_Unterrichtsfach_Klasse1`
    FOREIGN KEY (`k_name`)
    REFERENCES `ecbookdb`.`klasse` (`k_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_id2`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecbookdb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
